module:
  entity:
    - metadata:
        id: 3a976287-f32a-45bd-8736-1456a6b1ed3e
        name: Semgrep
        description: Semgrep
        icon: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiB2aWV3Qm94PSIwIDAgMTYgMTYiPjxwYXRoIGZpbGw9Im5vbmUiIHN0cm9rZT0iIzhiZDVjYSIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiBkPSJNMyAxMC41YTIuNSAyLjUgMCAxIDAgMC01YTIuNSAyLjUgMCAwIDAgMCA1bTUgMGEyLjUgMi41IDAgMSAwIDAtNWEyLjUgMi41IDAgMCAwIDAgNW01IDBhMi41IDIuNSAwIDEgMCAwLTVhMi41IDIuNSAwIDAgMCAwIDUiLz48L3N2Zz4=
        type: scanner
      tags: [ vendor, company, security, sast ]
      object: semgrep

    - metadata:
        id: fbf8d2b5-587e-49c7-921d-c8ff580bcb4a
        name: CodeQL
        description: GitHub CodeQL
        icon: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiB2aWV3Qm94PSIwIDAgMzIgMzIiPjxwYXRoIGZpbGw9IiMyMDg4ZmYiIGQ9Ik0yNi44ODkgMjRINS4xMTFBMy4wNiAzLjA2IDAgMCAxIDIgMjFWMTFhMy4wNiAzLjA2IDAgMCAxIDMuMTExLTNoMjEuNzc4QTMuMDYgMy4wNiAwIDAgMSAzMCAxMXYxMGEzLjA2IDMuMDYgMCAwIDEtMy4xMTEgM001LjExMSAxMGExLjAyIDEuMDIgMCAwIDAtMS4wMzcgMXYxMGExLjAyIDEuMDIgMCAwIDAgMS4wMzcgMWgyMS43NzhhMS4wMiAxLjAyIDAgMCAwIDEuMDM3LTFWMTFhMS4wMiAxLjAyIDAgMCAwLTEuMDM3LTFaIi8+PHBhdGggZmlsbD0iIzIwODhmZiIgZD0iTTIyLjc0MSAxNWgtMi4wNzRhMSAxIDAgMSAxIDAtMmgyLjA3NGExIDEgMCAxIDEgMCAybTIuMDc0IDRoLTQuMTQ4YTEgMSAwIDEgMSAwLTJoNC4xNDhhMSAxIDAgMSAxIDAgMm0tMTIuNTk4LTNhMy40IDMuNCAwIDAgMS0uMjU2IDEuMzY5YTIuNjYgMi42NiAwIDAgMS0uNy45NzJsLjg2MyAxLjA0NWgtMS4xOWwtLjQ4Ny0uNTc2YTMuMSAzLjEgMCAwIDEtMS4wNTcuMTc5YTIuOTQgMi45NCAwIDAgMS0xLjQ0NC0uMzUzYTIuNTQgMi41NCAwIDAgMS0xLjAxLTEuMDIxQTMuMyAzLjMgMCAwIDEgNi41NjYgMTZhMy4zIDMuMyAwIDAgMSAuMzcyLTEuNjE5YTIuNTQgMi41NCAwIDAgMSAxLjAxLTEuMDE5YTMuMTQgMy4xNCAwIDAgMSAyLjg4NCAwYTIuNTUgMi41NSAwIDAgMSAxLjAxMiAxLjAxOUEzLjMgMy4zIDAgMCAxIDEyLjIxNyAxNm0tMy4yNjcuODg2aDEuMDg0bC40NDguNTU0YTEuNyAxLjcgMCAwIDAgLjMyNS0uNmEyLjcgMi43IDAgMCAwIC4xMTctLjg0YTIuMSAyLjEgMCAwIDAtLjQxOS0xLjQxM2ExLjQgMS40IDAgMCAwLTEuMTEzLS40ODdhMS40IDEuNCAwIDAgMC0xLjExNC40ODhBMi4xIDIuMSAwIDAgMCA3Ljg2IDE2YTIuMSAyLjEgMCAwIDAgLjQxOCAxLjQxMmExLjQgMS40IDAgMCAwIDEuMTE0LjQ4OWExLjcgMS43IDAgMCAwIC4zMy0uMDMyWk0xMy42IDE5di02aDEuMjc2djQuOTg2aDIuNTg3VjE5WiIvPjwvc3ZnPg==
        type: scanner
      tags: [ vendor, security, sast ]
      object: codeql

    - metadata:
        id: 1221f1f6-910c-4fa5-b2b8-9f2109841a40
        name: Fortify SCA
        description: MicroFocus Fortify SCA
        icon: data:image/svg+xml;base64,PHN2ZyBoZWlnaHQ9IjEwMCIgdmlld0JveD0iMCAwIDQuNiA0LjYiIHdpZHRoPSIxMDAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHBhdGggZD0iTTAgMHY0LjZoNC42VjB6bTQuMjA1IDAuNDg3djIuMDI1YzAgMC4yMTIgMC4wMjggMC40NDYgLTAuMDAyIDAuNjU2IC0wLjA2MSAwLjQzNSAtMC4zNDQgMC44MTcgLTAuNzUzIDAuOTg0IC0wLjIzNCAwLjA5NSAtMC40NzIgMC4wODkgLTAuNzIgMC4wODlIMC41NTdjLTAuMDI1IDAgLTAuMDc3IDAuMDEgLTAuMDk1IC0wLjAwOSAtMC4wMiAtMC4wMjEgLTAuMDExIC0wLjA3IC0wLjAxMSAtMC4wOTZ2LTIuMTMxYzAgLTAuMjc1IC0wLjAwMiAtMC41NDEgMC4xMTMgLTAuNzk3IDAuMTU1IC0wLjM0NSAwLjQ3MSAtMC42MDMgMC44MzkgLTAuNjg4IDAuMjUyIC0wLjA1OCAwLjUyNiAtMC4wMzEgMC43ODMgLTAuMDMxem0tMy4yMDMgMy4yMWgxLjdjMC4yNzEgMCAwLjU1NSAwLjAyMyAwLjc2MiAtMC4xOTFhMC44MzYgMC44MzYgMCAwIDAgMC4xMTcgLTAuMTU1YzAuMDk2IC0wLjE2MyAwLjA4NyAtMC4zNDYgMC4wODcgLTAuNTI5VjEuMTA4YzAgLTAuMDE4IDAuMDA3IC0wLjA1MyAtMC4wMDUgLTAuMDY4IC0wLjAxMyAtMC4wMTcgLTAuMDU0IC0wLjAwOSAtMC4wNzMgLTAuMDA5SDEuODc3Yy0wLjIgMCAtMC4zODggLTAuMDA2IC0wLjU2NCAwLjEwNCAtMC4xNjIgMC4xIC0wLjI4MSAwLjI4NyAtMC4zMDkgMC40NzUgLTAuMDE2IDAuMTEgLTAuMDAyIDAuMjM0IC0wLjAwMiAwLjM0NnYxLjc0M00xLjcyMiAyLjY0NnYwLjg1NGMwIDAuMDE3IDAuMDA1IDAuMDQ2IC0wLjAxMSAwLjA1OCAtMC4wMTcgMC4wMTMgLTAuMDYxIDAuMDA1IC0wLjA4MSAwLjAwNUgxLjI0OWMtMC4wMTggMCAtMC4wNTMgMC4wMDcgLTAuMDY4IC0wLjAwNSAtMC4wMTcgLTAuMDEzIC0wLjAwOSAtMC4wNTQgLTAuMDA5IC0wLjA3M1YxLjg2M2MwIC0wLjE2OCAtMC4wMDQgLTAuMzMxIDAuMTAyIC0wLjQ3MyAwLjE1OSAtMC4yMTMgMC4zODMgLTAuMjEyIDAuNjI1IC0wLjIxMmgxLjQ0NmMwLjA0NCAwIDAuMTIgLTAuMDE1IDAuMTYxIDAuMDAyIDAuMDI4IDAuMDEyIDAuMDE1IDAuMDkyIDAuMDE1IDAuMTE4djAuMzI1YzAgMC4wMjUgMC4wMTIgMC4wOSAtMC4wMTUgMC4xMDIgLTAuMDMxIDAuMDE0IC0wLjA4NiAwLjAwNCAtMC4xMTkgMC4wMDRIMi4wOTZjLTAuMDc4IDAgLTAuMTc5IC0wLjAxNyAtMC4yNTQgMC4wMDMgLTAuMTIxIDAuMDMzIC0wLjE2NCAwLjIzNiAtMC4xMjMgMC4zNDIgMC4wMTQgMC4wMzcgMC4wNTcgMC4wMjggMC4wODggMC4wMjhIMy4wNjljMC4wMjggMCAwLjA3MiAtMC4wMDggMC4wOTggMC4wMDIgMC4wMjggMC4wMTIgMC4wMTUgMC4wOTIgMC4wMTUgMC4xMThWMi41NGMwIDAuMDI0IDAuMDEyIDAuMDkyIC0wLjAxNSAwLjEwMyAtMC4wMzMgMC4wMTQgLTAuMDkxIDAuMDAyIC0wLjEyNiAwLjAwMmgtMC4yOTZ6IiBmaWxsPSIjNGRhOGVkIi8+PC9zdmc+
        type: scanner
      tags: [ vendor, security, sast ]
      object: fortify

    - metadata:
        id: 4bc942e3-04a2-406c-bba3-cace9a5413cc
        name: Snyk
        description: Snyk
        icon: data:image/svg+xml;base64,0==
        type: scanner
      tags: [ vendor, company, security, sast ]
      object: Snyk

    - metadata:
        id: 12f8dbb5-d40c-4a90-bd2c-42d9a793ef37
        name: BurpSuite
        description: Portswigger BurpSuite
        icon: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMDAiIGhlaWdodD0iMTAwIiB2aWV3Qm94PSIwIDAgMjQgMjQiPjxwYXRoIGZpbGw9IiNlODY2NDUiIGQ9Ik0wIDB2MjRoMjRWMFptMTEuMDYzIDMuMzU3aDEuODc0djIuNzU2TDEwLjQxIDkuMmgyLjUyN3YzLjc0OGg0LjU3OWwtNC41NzggNS41OTJ2Mi4xMDRoLTEuODc2di0yLjc1OEwxMy41OSAxNC44aC0yLjUyN3YtMy43NWgtNC41OGw0LjU4LTUuNTkyWiIvPjwvc3ZnPg==
        type: scanner
      tags: [ vendor, security, dast ]
      object: burpsuite

    - metadata:
        id: 4cfc0e8b-4bba-40bf-9340-2717549aea82
        name: Invicti
        description: Invicti, formerly Netsparker
        icon: data:image/svg+xml;base64,0==
        type: scanner
      tags: [ vendor, company, security, dast ]
      object: Invicti

    - metadata:
        id: 1d07ae9f-72d3-45c0-9fdf-24f9a6e66686
        name: Acunetix
        description: Acunetix, AWVS
        icon: data:image/svg+xml;base64,0==
        type: scanner
      tags: [ vendor, security, dast ]
      object: Acunetix